#!/bin/sh
while read local_ref local_oid remote_ref remote_oid; do
    case "$local_oid" in
        0000000000000000000000000000000000000000) continue ;;
    esac
    python scripts/check_git_secrets.py --history "$local_oid" || exit 1
done
